[server]
account_data_path = "/home/arch/.orpheus/account-data"  # where the account registry is stored
bind_address = "0.0.0.0:31078"  # we want port 31078 over all interfaces (0.0.0.0), over TCP obviously
